const mongoose = require('mongoose');

const GDAarticles = 
        [{
        title: 'Pourquoi l\'Activité Physique va vous faire sauter au plafond!',
        subtitle: 'Le centre de lutte contre le cancer Henri Becquerel à Rouen a ouvert un pôle sport et cancer. Stéphane Jauffret, champion du monde de boxe thaï et praticien en thérapie sportive, y aide les malades à lutter contre la maladie.',
        author: 'Presse',
        content: 
        "<p>Depuis le 12 avril, le service 'soins intensifs d\'hématologie' du centre Henri Becquerel à Rouen renferme un pôle 'sport et cancer'. Stéphane Jauffret, triple champion du monde de boxe thaï accompagne les patients atteints d\'une pathologie type leucémie, lymphome ou myélome.</p> <br><p style='font-style: italic; padding-top: 1.5vh; padding-bottom: 1.5vh'> Sa mission : les aider à se battre contre leur maladie.</p><p> Parfois l\'activité se pratique sans que le patient ne quitte son lit d\'hôpital. Plutôt que d\'être <span style='font-style: italic'>'un frein à l\'activité physique'</span>, le praticien en thérapie sportive utilise le lit comme un support à l\'exercice. <br>Alors que le cancer épuise l\'organisme, Stéphane Jauffret prodigue ses conseils pour que ses patients se réapproprient leur corps en le renforçant. Il leur donne des clés pour mieux respirer, réapprendre à bouger, à bien s\'étirer. Les exercices adaptés au cas par cas préviennent notamment le relâchement musculaire et contribuent à rendre l\'organisme et le mental plus fort. <span style= 'font-weight: bold'>Objectif : mieux lutter contre la maladie et réduire les effets secondaires des traitements.</span> <br>Le boxeur de haut niveau a été formé à la thérapie sportive sous une méthode portant le nom de 'Médiété'. Elle 'permet de travailler avec le patient, en chambre ou en collectif, que la personne soit alitée, assise ou debout', explique le spécialiste dans les colonnes de Paris Normandie. <span style='font-style: italic'>'Le Médiété part du relâchement musculaire, aborde la gestion du souffle et l\'action mécanique. Cela fait appel à la communication du corps, à la parole, à l\'hypnose.'</span></p>",
        },
        
    {
        title: 'Financée grâce à la Rochambelle, la sophrologie aide des malades du cancer à se sentir mieux',
        subtitle: 'Depuis 2006, La Rochambelle a permis de collecter 1 million d’euros pour la lutte contre le cancer. Parmi les projets financés, les ateliers de sophrologie qui ont lieu à Caen.',
        author: 'Mathilde Leclerc',
        content: "<p>140 000 euros, c’est la somme d’argent collectée par La Rochambelle en 2017. Au total, 20 000 femmes en rose ont couru à Caen (Calvados) pour financer 7 projets dont l’atelier de sophrologie. Mise en place à La Polyclinique du Parc, spécialisée en cancérologie, chirurgie et obstétrique, la sophrologie permet d’améliorer certains des effets secondaires liés aux traitements médicaux. L’atelier a pour objectif d’apprendre à se détendre, à gérer son stress et à diminuer la fatigue et les douleurs. Marie Cardinaux, bénéficiaire, revient sur son expérience.« J’ai découvert qu’on pouvait vivre avec la maladie » En à peine deux mois, le cancer de Marie s’est développé. J’allais très mal, j’avais deux chimiothérapies par semaine, du mois de mai au mois d’août. Lors de son rendez-vous médical, elle explique les problèmes respiratoires causés par les médicaments ainsi que le mal-être ressenti trois jours après la chimiothérapie. Son médecin lui conseille alors l’atelier de sophrologie. « J’en avais entendu parler mais j’ai attendu pour prendre rendez-vous. » Marie se décide et rencontre la sophrologue à la Polyclinique du Parc. Pendant 6 mois j’avais toujours des effets secondaires. Je me suis rendue chaque semaine à La Polyclinique du Parc et 15 jours après mon premier rendez-vous de sophrologie, sans médicament, j’allais beaucoup mieux. « La sophrologie a été un véritable miracle pour moi » Exercices respiratoires, détente musculaire, visualisations positives, ces techniques corporelles calment les symptômes de Marie. « J’enregistrais ce qu’Hélène me conseillait et je le répétais tous les jours. » Un soin qui a été vital pour son bien-être. « Je ne voyais aucune issue. J’ai cru que j’allais y rester. Puis j’ai découvert toutes les ressources en moi, j’ai découvert qu’on pouvait vivre avec la maladie. La sophrologie a été un véritable miracle pour moi ! »</p>",
       
                }
        ];

module.exports = GDAarticles;
